#!/usr/bin/env bash

cat <(echo '
const {
  _,
  every,
  matches,
  instanceOf,
  some,
  multi,
  reference,
  patroon,
  NoMatchError,
  UnevenArgumentCountError,
  PatroonError
} = require("./src/index")


') - | node -p
